<?xml version="1.0" encoding="utf-8"?><Database Name="DBTest" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=danielssql234.database.windows.net;Initial Catalog=DBTest;Persist Security Info=True;User ID=testuser" SettingsObjectName="ExternalDB_Console.Properties.Settings" SettingsPropertyName="DBTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Animal" Member="Animals">
    <Type Name="Animal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Animal_AnimalZoo" Member="AnimalZoos" ThisKey="Id" OtherKey="AnimalId" Type="AnimalZoo" />
    </Type>
  </Table>
  <Table Name="dbo.Zoo" Member="Zoos">
    <Type Name="Zoo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Zoo_AnimalZoo" Member="AnimalZoos" ThisKey="Id" OtherKey="ZooId" Type="AnimalZoo" />
    </Type>
  </Table>
  <Table Name="dbo.AnimalZoo" Member="AnimalZoos">
    <Type Name="AnimalZoo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZooId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnimalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Animal_AnimalZoo" Member="Animal" ThisKey="AnimalId" OtherKey="Id" Type="Animal" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Zoo_AnimalZoo" Member="Zoo" ThisKey="ZooId" OtherKey="Id" Type="Zoo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>